name: CI for internal branches
trigger:
    manual:
    push:
      types: [ branch ]
      branches: [ "main" ]
      notification:
        when: [ failure ]
        to: [ "7595802602588114657" ]
jobs:
  unittest:
    image: hub.byted.org/compile/bolt_compile_img:1.0.0.55
    envs:
      CCACHE_REMOTE_STORAGE: "redis://bolt-ccache-redis.byted.org:6667"
      CCACHE_DIR: "/root/.ccache"
      CCACHE_MAXSIZE: "100G"
      CCACHE_REDIS_TLS: "1"
      CCACHE_REDIS_TLS_CA_FILE: "/opt/redis/certs/ca.crt"
      CCACHE_REDIS_TLS_CERT_FILE: "/opt/redis/certs/redis-client.crt"
      CCACHE_REDIS_TLS_KEY_FILE: "/opt/redis/certs/redis-client.key"
      http_proxy: "http://sys-proxy-rd-relay.byted.org:8118"
      https_proxy: "http://sys-proxy-rd-relay.byted.org:8118"
      no_proxy: ".byted.org,localhost,127.0.0.1,0.0.0.0,127.17.0.2,.cn"
      HTTP_PROXY: "http://sys-proxy-rd-relay.byted.org:8118"
      HTTPS_PROXY: "http://sys-proxy-rd-relay.byted.org:8118"
      NO_PROXY: ".byted.org,localhost,127.0.0.1,0.0.0.0,127.17.0.2,.cn"
    steps:
      - id: cache
        uses: actions/cache
        inputs:
          key: x86-${{month_of_year()}}
          paths:
            - /root/.ccache/
            - /root/.conan2/
      - name: Run Unit Tests
        commands:
          - conan remote remove bolt-dev && conan remote login test bolt -p Bolt2023!
          - bash ./scripts/setup-dev-env.sh
          - bash -c "source ~/.bashrc && make submodules && make unittest_release"
  gluten-cpp-ut:
    image: hub.byted.org/compile/bolt_compile_img:1.0.0.55
    envs:
      CCACHE_REMOTE_STORAGE: "redis://bolt-ccache-redis.byted.org:6667"
      CCACHE_DIR: "/root/.ccache"
      CCACHE_MAXSIZE: "100G"
      CCACHE_REDIS_TLS: "1"
      CCACHE_REDIS_TLS_CA_FILE: "/opt/redis/certs/ca.crt"
      CCACHE_REDIS_TLS_CERT_FILE: "/opt/redis/certs/redis-client.crt"
      CCACHE_REDIS_TLS_KEY_FILE: "/opt/redis/certs/redis-client.key"
      http_proxy: "http://sys-proxy-rd-relay.byted.org:8118"
      https_proxy: "http://sys-proxy-rd-relay.byted.org:8118"
      no_proxy: ".byted.org,localhost,127.0.0.1,0.0.0.0,127.17.0.2,.cn"
      HTTP_PROXY: "http://sys-proxy-rd-relay.byted.org:8118"
      HTTPS_PROXY: "http://sys-proxy-rd-relay.byted.org:8118"
      NO_PROXY: ".byted.org,localhost,127.0.0.1,0.0.0.0,127.17.0.2,.cn"
    steps:
      - id: cache
        uses: actions/cache
        inputs:
          key: x86-${{month_of_year()}}
          paths:
            - /root/.ccache/
            - /root/.conan2/
      - name: Gluten CPP UT
        commands:
          - conan remote remove bolt-dev && conan remote login test bolt -p Bolt2023!
          - bash ./scripts/setup-dev-env.sh
          - bash -c "source ~/.bashrc && make submodules && make release_spark && make install"
          - git ls-remote --exit-code --heads git@code.byted.org:olap/gluten.git ${{Head.Branch}} >/dev/null 2>&1 && export GLUTEN_BRANCH=${{Head.Branch}} || export GLUTEN_BRANCH=${{Event.Change.Target.Branch}}
          - bash -c "source ~/.bashrc && git clone --depth=1 --branch ${GLUTEN_BRANCH} git@code.byted.org:olap/gluten.git && cd gluten && BUILD_VERSION=${GLUTEN_BRANCH} make cpp-test-release"

  backend-bolt-spark-ut:
    name: backend-bolt-spark-ut
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/compile/bolt_compile_img:1.0.0.55
    timeout: 240
    envs:
      CUSTOM_BUILD_VERSION: ${{Head.Branch}}
      CCACHE_REMOTE_STORAGE: "redis://bolt-ccache-redis.byted.org:6667"
      CCACHE_DIR: "/root/.ccache"
      CCACHE_MAXSIZE: "100G"
      CCACHE_REDIS_TLS: "1"
      CCACHE_REDIS_TLS_CA_FILE: "/opt/redis/certs/ca.crt"
      CCACHE_REDIS_TLS_CERT_FILE: "/opt/redis/certs/redis-client.crt"
      CCACHE_REDIS_TLS_KEY_FILE: "/opt/redis/certs/redis-client.key"
      SPARK_LOCAL_HOSTNAME: "localhost"
      ci_no_proxy: '*'
    auto-checkout: false
    steps:
      - id: cache
        uses: actions/cache
        inputs:
          key: x86-${{month_of_year()}}
          paths:
            - /root/.ccache/
            - /root/.m2/repository/
      - name: backend-bolt-spark-ut
        continue-on-error: true
        commands:
          - export ARROW_THRIFT_URL=https://repo.huaweicloud.com/apache/thrift/0.16.0/thrift-0.16.0.tar.gz
          - git ls-remote --exit-code --heads git@code.byted.org:olap/gluten.git ${{Head.Branch}} >/dev/null 2>&1 && export GLUTEN_BRANCH=${{Head.Branch}} || export GLUTEN_BRANCH=${{Event.Change.Target.Branch}}
          - git clone --depth=1 git@code.byted.org:olap/gluten.git -b ${GLUTEN_BRANCH}
          - cd gluten
          - bash -x dev/build.sh > ci_log.txt 2>&1
          - bash -c "set -o pipefail; make spark-ut-test >> ci_log.txt 2>&1"
      - name: Upload Log
        uses: actions/upload-artifact
        inputs:
          name: ci_log
          path: gluten/ci_log.txt

  backend-bolt-spark-slow-ut:
    name: backend-bolt-spark-slow-ut
    runs-on:
      spec: m1.8xlarge
    image: hub.byted.org/compile/bolt_compile_img:1.0.0.55
    timeout: 240
    envs:
      CUSTOM_BUILD_VERSION: ${{Head.Branch}}
      CCACHE_REMOTE_STORAGE: "redis://bolt-ccache-redis.byted.org:6667"
      CCACHE_DIR: "/root/.ccache"
      CCACHE_MAXSIZE: "100G"
      CCACHE_REDIS_TLS: "1"
      CCACHE_REDIS_TLS_CA_FILE: "/opt/redis/certs/ca.crt"
      CCACHE_REDIS_TLS_CERT_FILE: "/opt/redis/certs/redis-client.crt"
      CCACHE_REDIS_TLS_KEY_FILE: "/opt/redis/certs/redis-client.key"
      SPARK_LOCAL_HOSTNAME: "localhost"
      ci_no_proxy: '*'
    auto-checkout: false
    steps:
      - id: cache
        uses: actions/cache
        inputs:
          key: x86-${{month_of_year()}}
          paths:
            - /root/.ccache/
            - /root/.m2/repository/
      - name: backend-bolt-spark-slow-ut
        continue-on-error: true
        commands:
          - export ARROW_THRIFT_URL=https://repo.huaweicloud.com/apache/thrift/0.16.0/thrift-0.16.0.tar.gz
          - git ls-remote --exit-code --heads git@code.byted.org:olap/gluten.git ${{Head.Branch}} >/dev/null 2>&1 && export GLUTEN_BRANCH=${{Head.Branch}} || export GLUTEN_BRANCH=${{Event.Change.Target.Branch}}
          - git clone --depth=1 git@code.byted.org:olap/gluten.git -b ${GLUTEN_BRANCH}
          - cd gluten
          - bash -x dev/build.sh > ci_log.txt 2>&1
          - bash -c "set -o pipefail;make spark-ut-slow-test >> ci_log.txt 2>&1"
      - name: Upload Log
        uses: actions/upload-artifact
        inputs:
          name: ci_log
          path: gluten/ci_log.txt
